# Лабораторная работа 2
**Выполнила:** [Mamadova M.S]

## 1. Анализ проблемной области, бизнес-целей и технических целей

В данной работе выбраны три набора данных из финансовой и HR-сфер:
1. **Цены на золото (`FINAL_USO.csv`)** — финансовый рынок, драгоценные металлы.
2. **Цены на акции Starbucks (`Starbucks Dataset.csv`)** — фондовый рынок, акции ритейла.
3. **Зарплаты в Data Science (`ds_salaries.csv`)** — рынок труда в IT.

### Бизнес-цели и эффект для бизнеса:
1. **Золото:** Прогнозирование цены закрытия для принятия инвестиционных решений. *Эффект:* Снижение рисков при торговле на бирже, максимизация прибыли.
2. **Starbucks:** Прогнозирование стоимости акций. *Эффект:* Помощь трейдерам в определении точек входа и выхода из позиций.
3. **Зарплаты:** Анализ и предсказание уровня зарплаты для конкретной должности. *Эффект:* Снижение затрат HR-отдела на рекрутинг, удержание сотрудников без переплат, планирование ФОТ.

In [24]:
import pandas as pd
from IPython.display import display

# Загружаем файлы с помощью библиотеки Pandas
gold_df = pd.read_csv("data/FINAL_USO.csv")
starbucks_df = pd.read_csv("data/Starbucks Dataset.csv")
salaries_df = pd.read_csv("data/ds_salaries.csv")

print(f"Данные загружены. Размер датасета по золоту: {gold_df.shape[0]} строк и {gold_df.shape[1]} колонок.")

Данные загружены. Размер датасета по золоту: 1718 строк и 81 колонок.

### 2. Анализ сведений и проблемная область
*   **Золото и Starbucks:** Это финансовая сфера (биржа). Проблема в том, что цены на золото и акции меняются каждый день. Наша задача — научиться предсказывать, какая будет цена закрытия, чтобы помочь трейдерам вовремя покупать или продавать и не терять деньги.
*   **Зарплаты:** Это сфера работы и подбора персонала (HR). Проблема в том, что компаниям сложно понять, сколько денег справедливо платить специалисту с определенным опытом и должностью. Наша задача — предсказать размер зарплаты на основе данных о сотруднике, чтобы компании не переплачивали и могли планировать бюджет.

In [25]:
print("--- Первые строки данных по золоту ---")
display(gold_df.head(2))
print("--- Первые строки данных по зарплатам ---")
display(salaries_df.head(2))

--- Первые строки данных по золоту ---

,Date,Open,High,Low,Close,Adj Close,Volume,SP_open,SP_high,SP_low,...,GDX_Low,GDX_Close,GDX_Adj Close,GDX_Volume,USO_Open,USO_High,USO_Low,USO_Close,USO_Adj Close,USO_Volume
0,2011-12-15,154.740005,154.949997,151.710007,152.330002,152.330002,21521900,123.029999,123.199997,121.989998,...,51.570000,51.68,48.973877,20605600,36.900002,36.939999,36.049999,36.130001,36.130001,12616700
1,2011-12-16,154.309998,155.369995,153.899994,155.229996,155.229996,18124300,122.230003,122.949997,121.300003,...,52.040001,52.68,49.921513,16285400,36.180000,36.500000,35.730000,36.270000,36.270000,12578800

--- Первые строки данных по зарплатам ---

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S

### 3. Анализ содержимого (объект, атрибуты, связи)
*   **Объект наблюдения:** Для золота и кофе (биржа) — это один торговый день. Для зарплат — это один конкретный сотрудник.
*   **Атрибуты (столбцы):** В биржевых данных мы смотрим на цены (открытия, закрытия, максимум, минимум) и объем торгов. В данных по зарплатам мы смотрим на опыт человека (`experience_level`), его должность (`job_title`) и страну.
*   **Связи между объектами:** В золоте и кофе есть связь по времени — сегодняшняя цена зависит от вчерашней. А в зарплатах люди друг от друга не зависят (зарплата одного программиста не зависит от зарплаты другого в этой таблице).

In [26]:
# Выводим названия колонок (атрибутов) красиво, по одной на строку
print("=== АТРИБУТЫ (КОЛОНКИ) ДЛЯ ЗОЛОТА ===")
for column in gold_df.columns:
    print(f"- {column}")

print("\n=== АТРИБУТЫ (КОЛОНКИ) ДЛЯ ЗАРПЛАТ ===")
for column in salaries_df.columns:
    print(f"- {column}")

=== АТРИБУТЫ (КОЛОНКИ) ДЛЯ ЗОЛОТА ===
- Date
- Open
- High
- Low
- Close
- Adj Close
- Volume
- SP_open
- SP_high
- SP_low
- SP_close
- SP_Ajclose
- SP_volume
- DJ_open
- DJ_high
- DJ_low
- DJ_close
- DJ_Ajclose
- DJ_volume
- EG_open
- EG_high
- EG_low
- EG_close
- EG_Ajclose
- EG_volume
- EU_Price
- EU_open
- EU_high
- EU_low
- EU_Trend
- OF_Price
- OF_Open
- OF_High
- OF_Low
- OF_Volume
- OF_Trend
- OS_Price
- OS_Open
- OS_High
- OS_Low
- OS_Trend
- SF_Price
- SF_Open
- SF_High
- SF_Low
- SF_Volume
- SF_Trend
- USB_Price
- USB_Open
- USB_High
- USB_Low
- USB_Trend
- PLT_Price
- PLT_Open
- PLT_High
- PLT_Low
- PLT_Trend
- PLD_Price
- PLD_Open
- PLD_High
- PLD_Low
- PLD_Trend
- RHO_PRICE
- USDI_Price
- USDI_Open
- USDI_High
- USDI_Low
- USDI_Volume
- USDI_Trend
- GDX_Open
- GDX_High
- GDX_Low
- GDX_Close
- GDX_Adj Close
- GDX_Volume
- USO_Open
- USO_High
- USO_Low
- USO_Close
- USO_Adj Close
- USO_Volume

=== АТРИБУТЫ (КОЛОНКИ) ДЛЯ ЗАРПЛАТ ===
- work_year
- experience_level
- employment_type
- job_title
- salary
- salary_currency
- salary_in_usd
- employee_residence
- remote_ratio
- company_location
- company_size

### 4. Бизнес-цели и эффект
1. **Золото и кофе (Starbucks):** 
   * *Цель:* Научиться предсказывать, какая будет цена закрытия.
   * *Эффект:* Трейдеры и инвесторы будут знать, когда покупать, а когда продавать, чтобы заработать и не потерять деньги.

2. **Зарплаты:** 
   * *Цель:* Научиться предсказывать, сколько нужно платить специалисту.
   * *Эффект:* Компания (HR-отдел) не будет переплачивать лишнего, сможет нормально спланировать бюджет и предложить сотруднику адекватную зарплату, чтобы он не уволился.

In [27]:
import pandas as pd

# Создаем красивую сводную таблицу с итогами
summary_data = {
    'Датасет': ['Золото', 'Кофе (Starbucks)', 'Зарплаты'],
    'Бизнес-цель': ['Предсказать цену', 'Предсказать цену', 'Предсказать зарплату'],
    'Количество записей': [gold_df.shape[0], starbucks_df.shape[0], salaries_df.shape[0]]
}

summary_df = pd.DataFrame(summary_data)

print("=== СВОДКА ПО ДАННЫМ ДЛЯ БИЗНЕСА ===")
# Выводим красивую таблицу
display(summary_df)

=== СВОДКА ПО ДАННЫМ ДЛЯ БИЗНЕСА ===

            Датасет           Бизнес-цель  Количество записей
0            Золото      Предсказать цену                1718
1  Кофе (Starbucks)      Предсказать цену                8036
2          Зарплаты  Предсказать зарплату                3755

### 5. Цели технического проекта (Вход и Целевой признак)
В машинном обучении мы всегда делим данные на две части: то, что мы знаем (Вход / X), и то, что хотим предсказать (Цель / Y).

1. **Золото:** 
   * *Вход (X):* цены `Open`, `High`, `Low`. 
   * *Цель (Y):* цена закрытия `Close`.
   * *Тип задачи:* Регрессия (предсказываем конкретное число — цену в долларах).

2. **Зарплаты:** 
   * *Вход (X):* опыт (`experience_level`), должность (`job_title`), локация (`company_location`). 
   * *Цель (Y):* зарплата `salary_in_usd`.
   * *Тип задачи:* Тоже регрессия (предсказываем конкретную сумму зарплаты в долларах).

In [28]:
print("=== ЧТО МЫ ЗНАЕМ (X) И ЧТО ПРЕДСКАЗЫВАЕМ (Y) ===\n")

# 1. Для золота
X_finance = gold_df[['Open', 'High', 'Low']]
y_finance = gold_df['Close']

print("1. ДЛЯ ЗОЛОТА:")
print("   Входные признаки (X):")
for col in X_finance.columns:
    print(f"   - {col}") # Красиво выводим каждую колонку с новой строки
print(f"   Предсказываем (Y): {y_finance.name}\n")

# 2. Для зарплат
X_hr = salaries_df[['experience_level', 'job_title', 'company_location']]
y_hr = salaries_df['salary_in_usd']

print("2. ДЛЯ ЗАРПЛАТ:")
print("   Входные признаки (X):")
for col in X_hr.columns:
    print(f"   - {col}")
print(f"   Предсказываем (Y): {y_hr.name}")

=== ЧТО МЫ ЗНАЕМ (X) И ЧТО ПРЕДСКАЗЫВАЕМ (Y) ===

1. ДЛЯ ЗОЛОТА:
   Входные признаки (X):
   - Open
   - High
   - Low
   Предсказываем (Y): Close

2. ДЛЯ ЗАРПЛАТ:
   Входные признаки (X):
   - experience_level
   - job_title
   - company_location
   Предсказываем (Y): salary_in_usd

### 6. Определение проблем данных
В любых данных могут быть «болячки». В наших датасетах есть две главные проблемы:
1. **Выбросы (аномалии):** Это числа, которые сильно отличаются от остальных. Например, если у всех программистов зарплата 100 тысяч, а у директора — 5 миллионов, это выброс. В финансах (золото и кофе) выбросы бывают из-за кризисов или паники на бирже, когда цена резко падает или взлетает.
2. **Пропуски:** Это пустые клетки в таблице (NaN). Они могут появляться, если биржа не работала в выходной день или если человек не указал свой опыт в анкете.

In [29]:
print("=== ПРОВЕРКА НА ПРОБЛЕМЫ ===")

# 1. Проверяем пропуски (пустые клетки)
gold_missing = gold_df.isnull().sum().sum()
sal_missing = salaries_df.isnull().sum().sum()
print(f"1. Пропуски (пустые клетки) в золоте: {gold_missing} шт.")
print(f"   Пропуски в зарплатах: {sal_missing} шт.")

# 2. Доказываем наличие выбросов в зарплатах
print("\n2. Доказательство выбросов в зарплатах:")
max_sal = salaries_df['salary_in_usd'].max()
mean_sal = salaries_df['salary_in_usd'].mean()
print(f"   Средняя зарплата: {mean_sal:.0f} $")
print(f"   Самая высокая зарплата (выброс): {max_sal} $")
print("   (Видно, что максимум сильно больше среднего — это и есть выброс)")

=== ПРОВЕРКА НА ПРОБЛЕМЫ ===
1. Пропуски (пустые клетки) в золоте: 0 шт.
   Пропуски в зарплатах: 0 шт.

2. Доказательство выбросов в зарплатах:
   Средняя зарплата: 137570 $
   Самая высокая зарплата (выброс): 450000 $
   (Видно, что максимум сильно больше среднего — это и есть выброс)

### 7. Решение обнаруженных проблем
Мы не будем тупо удалять всё подряд, а подойдем с умом:
*   **Выбросы в финансах:** Мы их **оставляем**. Если в 2008 году цена золота рухнула, это не ошибка, а исторический факт. Удалять это нельзя, иначе модель не узнает, что кризисы бывают.
*   **Выбросы в зарплатах:** А вот в зарплатах огромные суммы директоров нам будут мешать. Мы **отрежем верхний 1%** (самые большие числа), чтобы модель не сбивала настройки на миллионерах.
*   **Пропуски:** Мы их обработаем в 10-м пункте (удалим или заполним).

In [30]:
print("=== РЕШЕНИЕ ПРОБЛЕМЫ ВЫБРОСОВ В ЗАРПЛАТАХ ===")

# Находим 99-й процентиль (отсекаем самые extreme значения)
q_99 = salaries_df['salary_in_usd'].quantile(0.99)
print(f"Порог отсечения (99-й процентиль): {q_99:.0f} $")

# Оставляем только те строки, где зарплата меньше или равна порогу
salaries_filtered = salaries_df[salaries_df['salary_in_usd'] <= q_99]

print("\n--- РЕЗУЛЬТАТ ФИЛЬТРАЦИИ ---")
print(f"Было строк ДО фильтрации выбросов:    {len(salaries_df)}")
print(f"Стало строк ПОСЛЕ фильтрации (без 1%): {len(salaries_filtered)}")
print("Мы успешно убрали аномалии и сохранили остальные данные!")

=== РЕШЕНИЕ ПРОБЛЕМЫ ВЫБРОСОВ В ЗАРПЛАТАХ ===
Порог отсечения (99-й процентиль): 309400 $

--- РЕЗУЛЬТАТ ФИЛЬТРАЦИИ ---
Было строк ДО фильтрации выбросов:    3755
Стало строк ПОСЛЕ фильтрации (без 1%): 3718
Мы успешно убрали аномалии и сохранили остальные данные!

### 8. Оценка качества данных
Наши данные — качественные и надежные. 
*   **Информативность:** Высокая, потому что у нас много столбцов (цены, объемы, опыт, должности), из которых модель сможет сделать выводы.
*   **Соответствие реальным данным:** Данные не выдуманные, а скачаны с настоящих бирж и из реальных опросов.
*   **Согласованность меток:** Нет бреда. Если написано, что цена золота 1000$, а дата 2020 год — это правда.

In [31]:
print("=== ПРОВЕРКА КАЧЕСТВА (ДУБЛИКАТЫ) ===")

# Проверяем, нет ли повторяющихся строк
dups_gold = gold_df.duplicated().sum()
dups_sal = salaries_df.duplicated().sum()

print(f"Полных дубликатов (копий) в золоте:   {dups_gold} шт.")
print(f"Полных дубликатов (копий) в зарплатах: {dups_sal} шт.")
print("Если 0, значит копий нет, и данные чистые!")

=== ПРОВЕРКА КАЧЕСТВА (ДУБЛИКАТЫ) ===
Полных дубликатов (копий) в золоте:   0 шт.
Полных дубликатов (копий) в зарплатах: 1171 шт.
Если 0, значит копий нет, и данные чистые!

### 9. Разбиение данных на выборки
Нельзя учить модель на всех данных сразу — она просто «зазубрит» ответы и провалится на реальном экзамене. Поэтому мы делим данные на три части:
1. **Обучающая (Train) — 60%:** Учебник. По нему модель учится.
2. **Контрольная (Validation) — 20%:** Пробный экзамен. На нем мы проверяем настройки модели.
3. **Тестовая (Test) — 20%:** Выпускной экзамен. Модель его никогда не видела, и мы честно проверяем, чему она научилась.

In [32]:
from sklearn.model_selection import train_test_split

print("=== РАЗБИЕНИЕ ДАННЫХ НА ВЫБОРКИ ===")

# Сначала отделяем 40% данных для валидации и теста
train_data, temp_data = train_test_split(gold_df, test_size=0.4, random_state=42)
# Затем делим эти 40% пополам (по 20%)
val_data, test_data = train_test_split(temp_data, test_size=0.5, random_state=42)

print(f"1. Обучающая выборка (Train, 60%):     {len(train_data)} строк")
print(f"2. Контрольная выборка (Validation, 20%): {len(val_data)} строк")
print(f"3. Тестовая выборка (Test, 20%):          {len(test_data)} строк")
print(f"ИТОГО: {len(train_data) + len(val_data) + len(test_data)} строк (все данные на месте)")

=== РАЗБИЕНИЕ ДАННЫХ НА ВЫБОРКИ ===
1. Обучающая выборка (Train, 60%):     1030 строк
2. Контрольная выборка (Validation, 20%): 344 строк
3. Тестовая выборка (Test, 20%):          344 строк
ИТОГО: 1718 строк (все данные на месте)

### 10. Устранение пропущенных данных
По заданию нужно было использовать три разных метода. Мы распределили их так:
1. **Удаление (`dropna`)** — для золота. Если за какой-то день нет данных, мы просто выбрасываем эту строчку, чтобы не гадать.
2. **Заполнение нулем (`fillna(0)`)** — для кофе. Если торгов не было, то логично поставить в объем торгов ноль.
3. **Заполнение средним (`fillna(mean)`)** — для зарплат. Если человек не указал зарплату, мы ставим среднюю по таблице, чтобы не терять информацию о его опыте и должности.

In [33]:
print("=== УСТРАНЕНИЕ ПРОПУСКОВ (3 МЕТОДА) ===")

# 1. Удаление
gold_cleaned = train_data.dropna()
print(f"1. Метод dropna(): было {len(train_data)} строк, осталось {len(gold_cleaned)} (удалены пустые).")

# 2. Заполнение нулем
starbucks_train, _ = train_test_split(starbucks_df, test_size=0.4, random_state=42)
starbucks_cleaned = starbucks_train.fillna(0)
print("2. Метод fillna(0): все пропуски в данных по кофе заменены на 0.")

# 3. Заполнение средним
salaries_train, _ = train_test_split(salaries_df, test_size=0.4, random_state=42)
salaries_mean = salaries_train.mean(numeric_only=True)
salaries_cleaned = salaries_train.fillna(salaries_mean)
print("3. Метод fillna(mean): все пропуски в зарплатах заменены на среднее значение.")

=== УСТРАНЕНИЕ ПРОПУСКОВ (3 МЕТОДА) ===
1. Метод dropna(): было 1030 строк, осталось 1030 (удалены пустые).
2. Метод fillna(0): все пропуски в данных по кофе заменены на 0.
3. Метод fillna(mean): все пропуски в зарплатах заменены на среднее значение.

### 11. Оценка сбалансированности выборок
Наши данные — это числа (цены). Но чтобы проверить, нет ли перекоса, я превратила задачу в «угадай, вырастет цена или упадет».
Я создала новый столбец `Target`: 
* Если завтрашняя цена больше сегодняшней — ставим `1` (цена выросла).
* Если меньше — ставим `0` (цена упала).
Затем я посчитала, сколько дней было с ростом, а сколько с падением. Если одних дней намного больше, чем других, это называется **дисбаланс**.

In [34]:
print("=== ОЦЕНКА СБАЛАНСИРОВАННОСТИ ===")

# Создаем копию данных и новый столбец Target
gold_class = train_data.copy()
gold_class['Target'] = (gold_class['Close'].shift(-1) > gold_class['Close']).astype(int)
gold_class = gold_class.dropna(subset=['Target']) # Удаляем последнюю строку (у нее нет "завтра")

# Считаем, сколько раз цена росла, а сколько падала
counts = gold_class['Target'].value_counts()

print("Сколько дней было с падением цены (0):", counts.get(0, 0))
print("Сколько дней было с ростом цены (1): ", counts.get(1, 0))
print("\n(Если числа сильно отличаются, значит есть дисбаланс)")

=== ОЦЕНКА СБАЛАНСИРОВАННОСТИ ===
Сколько дней было с падением цены (0): 518
Сколько дней было с ростом цены (1):  512

(Если числа сильно отличаются, значит есть дисбаланс)

### 12. Приращение данных (SMOTE и Undersampling)
Если в данных перекос (например, дней падения 500, а дней роста всего 300), модель может просто всегда отвечать «упадет» и будет права в 60% случаев. Чтобы её проучить, мы балансируем данные:
* **Oversampling (SMOTE):** Берет те 300 дней роста и создает на их основе искусственные копии, пока их не станет 500. Теперь у нас 500 на 500.
* **Undersampling:** Наоборот, берет 500 дней падения и удаляет оттуда лишние 200, чтобы осталось 300. Тоже получается 300 на 300.
Я применила оба метода из библиотеки `imbalanced-learn`.

In [35]:
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler

print("=== ПРИРАЩЕНИЕ ДАННЫХ ===")

# Отделяем признаки (X) от цели (y)
X = gold_class.drop(columns=['Target', 'Date'])
y = gold_class['Target']

# 1. Oversampling
print("\n1. Oversampling (SMOTE) - добавляем копии:")
smote = SMOTE(random_state=42)
X_over, y_over = smote.fit_resample(X, y)
print(f"   Было: {y.value_counts().to_dict()}")
print(f"   Стало: {y_over.value_counts().to_dict()}")
print("   (Классы сравнялись, добавились искусственные данные)")

# 2. Undersampling
print("\n2. Undersampling (RandomUnderSampler) - удаляем лишнее:")
undersampler = RandomUnderSampler(random_state=42)
X_under, y_under = undersampler.fit_resample(X, y)
print(f"   Было: {y.value_counts().to_dict()}")
print(f"   Стало: {y_under.value_counts().to_dict()}")
print("   (Классы сравнялись, удалили лишние данные большинства)")

=== ПРИРАЩЕНИЕ ДАННЫХ ===

1. Oversampling (SMOTE) - добавляем копии:

   Было: {0: 518, 1: 512}
   Стало: {0: 518, 1: 518}
   (Классы сравнялись, добавились искусственные данные)

2. Undersampling (RandomUnderSampler) - удаляем лишнее:
   Было: {0: 518, 1: 512}
   Стало: {0: 512, 1: 512}
   (Классы сравнялись, удалили лишние данные большинства)